### ISSUE TITLE
Things to do before (and after) year starts

### ISSUE THREAD

**Issue by grallucas** [grallucas/maic#1]
- [x] Rename "workshops" to "events"
- [x] Have an about-us blurb on landing page that links to a longer "about" page ("about" is also available in the toolbar?)
  - About can have:
    - [x] FAQ
    - [x] history of the club
- [x] Support an author tag in page markdown content
- [x] Link to workshops from news AND events if they are interactive presentations about AI news
- [x] Have some starter learning resources for the introductory workshops
- [x] Fill out other missing content (eboard, merch, etc)
- [x] Do we not have a specific section describing points and the leaderboard?
- [x] left-padding in "About"
- [x] "About Me" in contact
- [x] Correctly link "recent" in home
- [x] card padding in "contact" isn't consistent with other pages

Feel free to comment other items or progress on items

**Comment by Benja-Pauls** [comment]
Completed all tasks -- history of club partially added but may be cleaned in future. Old eboard badges added
